---
- hosts: tag_reddit-app
  serial: 1
  become: true
  pre_tasks:
    - include_tasks: reconfigure-nginx.yml
      vars:
        excluded_host: "{{ hostvars[inventory_hostname]['gce_public_ip'] }}"
      loop: "{{ groups['tag_reddit-balancer'] }}"
      loop_control:
        loop_var: balancer_item
  tasks:
    - name: copy site template
      become: true
      template:
        src: ../templates/index.html.j2
        dest: /var/www/html/index.html
        mode: 0644
  post_tasks:
    - include_tasks: reconfigure-nginx.yml
      loop: "{{ groups['tag_reddit-balancer'] }}"
      loop_control:
        loop_var: balancer_item
